matrix:
  - mpi_on
  - mpi_off

mpi_on:
  build:
    modules:
      - ninja
      - openmpi
    modules_package:
      - atlas:openmpi
      - eckit:openmpi
    dependencies:
      - ecmwf/ecbuild@develop
      - ecmwf/eckit@develop
      - ecmwf/fckit@develop
      - ecmwf/atlas@develop
      - ecmwf/eccodes@develop
    dependency_cmake_options:
      - ecmwf/atlas:-DENABLE_FORTRAN=ON
    parallel: 64
    ntasks: 16
    env:
      - CTEST_PARALLEL_LEVEL=1
      - OMPI_MCA_rmaps_base_oversubscribe=1
      - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
      - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions

mpi_off:
  build:
    modules:
      - ninja
    dependencies:
      - ecmwf/ecbuild@develop
      - ecmwf/eckit@develop
      - ecmwf/fckit@develop
      - ecmwf/atlas@develop
      - ecmwf/eccodes@develop
    dependency_cmake_options:
      - ecmwf/atlas:-DENABLE_FORTRAN=ON
    parallel: 64
