export const dom = {
  runTabBtn: document.getElementById("run-tab-btn"),
  setupTabBtn: document.getElementById("setup-tab-btn"),
  runPanel: document.getElementById("run-panel"),
  setupPanel: document.getElementById("setup-panel"),
  launchBtn: document.getElementById("launch"),
  devToggle: document.getElementById("dev-toggle"),
  status: document.getElementById("status"),
  runTabDot: document.getElementById("run-tab-dot"),
  setupTabDot: document.getElementById("setup-tab-dot"),
  output: document.getElementById("output"),
  dryRunToggle: document.getElementById("dry-run"),
  runModeRadios: document.querySelectorAll("input[name='run-mode']"),
  plumePane: document.getElementById("plume-pane"),
  emulatorPane: document.getElementById("emulator-pane"),
  gribPane: document.getElementById("grib-pane"),
  runControlPanel: document.getElementById("run-control-panel"),
  uploadButtons: document.querySelectorAll(".upload-btn"),
  runChecksBtn: document.getElementById("run-checks-btn"),
  checksStatus: document.getElementById("checks-status"),
  mapDiv: document.getElementById("equal-earth-map"),
  mapZoomInBtn: document.getElementById("map-zoom-in"),
  mapZoomOutBtn: document.getElementById("map-zoom-out"),
  mapPanToggleBtn: document.getElementById("map-pan-toggle"),
};
