export const uiState = {
  checksState: "idle",
  runStatus: "not-ready",
  executionMode: "full",
  optionsUnlocked: false,
  runContext: {
    runMode: "config",
    gribFileCount: null,
    emulatorConfigText: "",
  },
  stepSessionActive: false,
  stepCurrent: 0,
  stepLatest: 0,
  stepTotal: null,
  stepHasNext: false,
  stepRequestInFlight: false,
  stepHistory: {},
  stepMapImages: {},
  mapProjectionScale: 1,
  mapCenter: { lon: 0, lat: 0 },
  translateEnabled: false,
};
